{
    "custom-styles": {
    },
    "editor-colors": {
        "BackgroundColor": "#40352a",
        "BracketMatching": "#ebcb8b",
        "CodeFolding": "#00000000",
        "CurrentLine": "#4a3e31",
        "CurrentLineNumber": "#f3f4ee",
        "IconBorder": "#40352a",
        "IndentationLine": "#6a5845",
        "LineNumbers": "#e8e9e4",
        "MarkBookmark": "#00000000",
        "MarkBreakpointActive": "#00000000",
        "MarkBreakpointDisabled": "#00000000",
        "MarkBreakpointReached": "#00000000",
        "MarkError": "#00000000",
        "MarkExecution": "#00000000",
        "MarkWarning": "#00000000",
        "ModifiedLines": "#00000000",
        "ReplaceHighlight": "#7f414f",
        "SavedLines": "#00000000",
        "SearchHighlight": "#9b8066",
        "Separator": "#00000000",
        "SpellChecking": "#00000000",
        "TabMarker": "#706f6e",
        "TemplateBackground": "#00000000",
        "TemplateFocusedPlaceholder": "#00000000",
        "TemplatePlaceholder": "#00000000",
        "TemplateReadOnlyPlaceholder": "#00000000",
        "TextSelection": "#ac8e71",
        "WordWrapMarker": "#706f6e"
    },
    "metadata": {
        "author": "You",
        "license": "CC-BY-SA",
        "name": "Golden Harvest",
        "revision": 1
    },
    "text-styles": {
        "Alert": {
            "bold": true,
            "text-color": "#bf616a"
        },
        "Annotation": {
        },
        "Attribute": {
            "text-color": "#c3efb9"
        },
        "BaseN": {
        },
        "BuiltIn": {
        },
        "Char": {
            "text-color": "#a3be8c"
        },
        "Comment": {
            "italic": true,
            "text-color": "#706f6e"
        },
        "CommentVar": {
        },
        "Constant": {
        },
        "ControlFlow": {
        },
        "DataType": {
        },
        "DecVal": {
        },
        "Documentation": {
            "italic": true,
            "text-color": "#8fbccb"
        },
        "Error": {
            "text-color": "#7f414f",
            "underline": true
        },
        "Extension": {
        },
        "Float": {
        },
        "Function": {
            "text-color": "#c3efb9"
        },
        "Import": {
        },
        "Information": {
        },
        "Keyword": {
            "bold": true,
            "text-color": "#ebcb8b"
        },
        "Normal": {
            "background-color": "#40352a",
            "text-color": "#f3f4ee"
        },
        "Operator": {
            "text-color": "#e8e9e4"
        },
        "Others": {
        },
        "Preprocessor": {
            "text-color": "#ac8e71"
        },
        "RegionMarker": {
            "background-color": "#6a5845"
        },
        "SpecialChar": {
        },
        "SpecialString": {
        },
        "String": {
            "text-color": "#a3be8c"
        },
        "Variable": {
            "text-color": "#d8dccf"
        },
        "VerbatimString": {
        },
        "Warning": {
        }
    }
}
