look-and-feel: look-and-feel/*
	tar -cJf Utterly-Nord.tar.xz look-and-feel/* --transform="s/look-and-feel\///"

look-and-feel-solid: look-and-feel-solid/*
	tar -cJf Utterly-Nord-Solid.tar.xz look-and-feel-solid/* --transform="s/look-and-feel-solid\///"

colors: UtterlyNord.colors
	tar -czf Utterly-Nord-Colors.tar.gz UtterlyNord.colors

# sddm: sddm/*
# 	tar -cJf Utterly-Nord-SDDM.tar.xz sddm/* --transform="s/sddm/Utterly-Nord/"

clean:
	rm *.zip & rm *.tar.*
